# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate Cypress Report
on:
  push:
    branches: 
    - 'develop'

jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.18.0-chrome83-ff77
    steps:
      - uses: actions/checkout@v2

      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
          
      - name: Remove test reports
        run: npm run clean_reports
        
      - name: Run Cypress tests
        run: npm run test
        continue-on-error: true
        
      - name: Copy test execution videos and screenshots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots
          
      - name: Merge test reports
        run: npm run merge_report

      - name: Generate HTML report
        run: npm run generate_report_onPublic
      
      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Send email
        uses: dawidd6/action-send-mail@v2.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          # Literal body:
          body: Build job of ${{github.repository}} completed successfully!
          # Read file contents as body:
          #body: file://README.md
          to: saahmed@nisum.com
          from: Saqib Ahmed # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional attachments:
          attachments: https://saqibahmed440.github.io/cypressTraining/Test-Report.html

