name: E2E Test Run (Firefox)
on:
  push:
    branches: 
    - 'master'

jobs:
  cypress-test:
    name: Run e2e Test Firefox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies cypress
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          
      - name: Remove test reports
        run: npm run clean_reports

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: firefox
          headless: false
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
        continue-on-error: true          

      - name: Copy test execution videos and screenshots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots
          
      - name: Merge test reports
        run: npm run merge_report

      - name: Generate HTML report
        run: npm run generate_report_onPublic
      
      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
